<a href="https://colab.research.google.com/github/yoonyoung27/prac_python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Library
https://numpy.org/doc/stable/user/index.html

In [1]:
import numpy as np

###①벡터

In [2]:
print(np.array([1,2,3]),
      np.arange(10),
      np.arange(5,10))

[1 2 3] [0 1 2 3 4 5 6 7 8 9] [5 6 7 8 9]


####\* 벡터 연산

In [3]:
x = np.array([1,2,3,4,5,6,7,8])
y = np.array([3,4,5,6,7,8,9,10])
print(x+y,
      x*2,
      x[3])

[ 4  6  8 10 12 14 16 18] [ 2  4  6  8 10 12 14 16] 4


###②행렬

In [4]:
print(np.array([[1,2,3],[4,5,6]]))
print(np.zeros((2,10)))
print(np.ones((2,10)))
print(np.identity(3))
print(np.random.rand(2,3))
print(np.random.randn(2,3))

[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.80522681 0.52782849 0.18036544]
 [0.60853104 0.27743796 0.40070135]]
[[ 0.90441337 -1.10412372 -0.61483941]
 [-0.08058892  0.07904608 -0.26686297]]


* rand는 0이상 1이하의 균등분포를 나타낸다
* randn은 정규분포를 나타낸다

####\* 행렬 연산

In [5]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[3,2,1],[6,5,4],[9,8,7]])
print(x+y)
print(x*2)
print(x[1,2],
      x[1,0:2])

[[ 4  4  4]
 [10 10 10]
 [16 16 16]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
6 [4 5]


####\* 행렬 함수, 메서드(전용 함수)

* __<shape()>__ (행 개수, 열 개수)를 알려준다
* __<np.linalg.norm()>__ norm ?
* __<np.linalg.svd()>__ singular value decomposition ?
* __<np.linalg.cholesky()>__ cholesky decomposition ?

\* 행렬 연산 함수

* __<exp()>__ exponential 함수
* __<dot()>__ 행렬의 곱

\* 벡터와 행렬 변환

* __<reshape(x,y)>__ x행 y열의 행렬로 변환

In [6]:
print('1.', x.shape)
print('2.', np.exp(x))
print('3.', x.dot(y))
z = np.array([1,2,3,4,5,6])
print('4.', z.reshape(2,3))

1. (3, 3)
2. [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
3. [[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]
4. [[1 2 3]
 [4 5 6]]
